// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhH7ZLyh1-rrAt-ottnVIxYEd3uClWpIo',
    appId: '1:758119065984:web:eb349ebc09e0d4453c7965',
    messagingSenderId: '758119065984',
    projectId: 'canteen-frontend-seller',
    authDomain: 'canteen-frontend-seller.firebaseapp.com',
    storageBucket: 'canteen-frontend-seller.firebasestorage.app',
    measurementId: 'G-HEWFKQ4EC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM4ZheYm1b199Hg7kmKIRzc-efYJDUKvc',
    appId: '1:758119065984:android:05d11afac8c3b6283c7965',
    messagingSenderId: '758119065984',
    projectId: 'canteen-frontend-seller',
    storageBucket: 'canteen-frontend-seller.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUxH-CU3FSwtctNEikiAtBZr5nGUvaf-c',
    appId: '1:758119065984:ios:5d52a85bd732ca963c7965',
    messagingSenderId: '758119065984',
    projectId: 'canteen-frontend-seller',
    storageBucket: 'canteen-frontend-seller.firebasestorage.app',
    iosBundleId: 'com.example.canteenFrontendSeller',
  );
}
